import '@seed/element-plus-components/base/style/css'
import '@seed/element-plus-components/input/style/css'
import '@seed/element-plus-components/button/style/css'
import '@seed/element-plus-components/checkbox/style/css'
import '@seed/element-plus-components/checkbox-group/style/css'
import '@seed/element-plus-theme-chalk/el-transfer.css'
