printWidth: 100 # 每行的最大长度
tabWidth: 2 # 缩进的空格数
useTabs: false # 使用空格而不是制表符
semi: false # 在语句末尾不使用分号
singleQuote: true # 使用单引号而不是双引号
quoteProps: preserve # 保持对象属性的引号使用
jsxSingleQuote: false # 在 JSX 中使用双引号
bracketSameLine: false # 将多行元素的闭合括号放在新行
trailingComma: all # 对象和数组中，末尾添加逗号
bracketSpacing: true # 在对象文字中的括号之间添加空格
embeddedLanguageFormatting: auto # 自动格式化嵌入的代码
arrowParens: avoid # 箭头函数参数只有一个时省略括号
requirePragma: false # 不需要文件顶部的 @prettier 或 @format 注释
insertPragma: false # 不自动在文件顶部插入 @prettier 或 @format 注释
proseWrap: never # 格式化 Markdown 文件时处理换行符，never 从不换行。Prettier 会保留原始的换行符，不会自动换行。。
htmlWhitespaceSensitivity: css # 遵循 CSS 显示属性的空白敏感度
vueIndentScriptAndStyle: true # Vue 文件中的 <script> 和 <style> 标签内的代码缩进
endOfLine: auto # 保持现有的行尾符号
overrides: # 覆盖特定文件的配置
  - files: ['*.json5']
    options:
      singleQuote: false # JSON5 文件中使用双引号
      quoteProps: preserve # 保留对象属性的引号
  - files: ['*.yml']
    options:
      singleQuote: false # YAML 文件中使用双引号
