import '@seed/element-plus-components/base/style/css'
import '@seed/element-plus-components/input/style/css'
import '@seed/element-plus-components/tooltip/style/css'
import '@seed/element-plus-components/scrollbar/style/css'
import '@seed/element-plus-theme-chalk/el-mention.css'
