[package]
name = "books"
version = "0.1.1"
edition = "2021"

[dependencies]
async-graphql = "4.0.16"
slab = "0.4.2"
futures-util = "0.3.0"
futures-channel = "0.3.0"
once_cell = "1.0"
futures-timer = "3.0.2"
async-stream = "0.3.0"
