/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('@element-plus/components')['ElButton']
    ElCard: typeof import('@element-plus/components')['ElCard']
    ElCheckbox: typeof import('@element-plus/components')['ElCheckbox']
    ElConfigProvider: typeof import('@element-plus/components')['ElConfigProvider']
    ElDivider: typeof import('@element-plus/components')['ElDivider']
    ElForm: typeof import('@element-plus/components')['ElForm']
    ElFormItem: typeof import('@element-plus/components')['ElFormItem']
    ElIcon: typeof import('@element-plus/components')['ElIcon']
    ElInput: typeof import('@element-plus/components')['ElInput']
    ElMenu: typeof import('@element-plus/components')['ElMenu']
    ElMenuItem: typeof import('@element-plus/components')['ElMenuItem']
    ElScrollbar: typeof import('@element-plus/components')['ElScrollbar']
    ElSubMenu: typeof import('@element-plus/components')['ElSubMenu']
    ElTag: typeof import('@element-plus/components')['ElTag']
    ElTooltip: typeof import('@element-plus/components')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RovingFocusGroup: typeof import('./src/components/VvDropdown/src/roving-focus-group/src/RovingFocusGroup.vue')['default']
    RovingFocusGroupImpl: typeof import('./src/components/VvDropdown/src/roving-focus-group/src/RovingFocusGroupImpl.vue')['default']
    RovingFocusItem: typeof import('./src/components/VvDropdown/src/roving-focus-group/src/RovingFocusItem.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    VvDropdown: typeof import('./src/components/VvDropdown/src/VvDropdown.vue')['default']
    VvDropdownItem: typeof import('./src/components/VvDropdown/src/VvDropdownItem.vue')['default']
    VvDropdownItemImpl: typeof import('./src/components/VvDropdown/src/VvDropdownItemImpl.vue')['default']
    VvDropdownMenu: typeof import('./src/components/VvDropdown/src/VvDropdownMenu.vue')['default']
  }
}
